version: '3'

services:
  bundler:
    build:
      context: .
      dockerfile: docker/json-bundler/Dockerfile
    image: myparcelcom/json-bundler:v2-dev
    working_dir: /opt/spec
    volumes:
      - .:/opt/spec

  redoc:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    image: myparcelcom/api-specification:v4-dev
    volumes:
      - ./dist:/usr/share/nginx/html/dist/
      - ./src/index.html:/usr/share/nginx/html/index.html
      - ./src/myparcelcom.css:/usr/share/nginx/html/myparcelcom.css
      - ./src/myparcelcom.js:/usr/share/nginx/html/myparcelcom.js
    environment:
      SPEC_URL: /dist/swagger.json
      PAGE_FAVICON: favicon-16x16.png
    ports:
      - ${REDOC_PORT}:80
