version: '3'

services:
  bundler:
    build:
      context: ./docker/json-bundler
      dockerfile: Dockerfile
    image: myparcelcom/api-spec-bundler:v1-dev
    working_dir: /opt/spec
    volumes:
      - .:/opt/spec

  node:
    image: node:9.11
    working_dir: /opt/spec
    command: ./node_modules/.bin/gulp watch --port $GULP_PORT --specification-json-url $SPECIFICATION_JSON_URL --api-host $API_HOST --auth-host $AUTH_HOST
    volumes:
      - .:/opt/spec
    ports:
      - $GULP_PORT:$GULP_PORT
