version: '3'

services:
  bundler:
    build:
      context: ./docker/json-bundler
      dockerfile: Dockerfile
    image: myparcelcom/json-bundler
    working_dir: /opt/spec
    volumes:
      - .:/opt/spec

  validator:
    image: swaggerapi/swagger-validator
    working_dir: /opt/spec
    volumes:
      - ./dist:/opt/spec
