apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  namespace: ${NS}
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}
    revision: ${CIRCLE_SHA1}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
  template:
    metadata:
      labels:
        app: ${CIRCLE_PROJECT_REPONAME}
        revision: ${CIRCLE_SHA1}
    spec:
      containers:
        - name: ${CIRCLE_PROJECT_REPONAME}
          image: ${ECR_REGISTRY}/myparcelcom/api-specification:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  namespace: ${NS}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
