kind: Service
apiVersion: v1
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-svc
  namespace: ${NS}
spec:
  selector:
    app: ${CIRCLE_PROJECT_REPONAME}
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-ingress
  namespace: ${NS}
  annotations:
    kubernetes.io/ingress.class: "nginx-${NS}"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api-specification
spec:
  rules:
    - host: ${APP_DOMAIN}
      http:
        paths:
          - path: /api-specification
            backend:
              serviceName: ${CIRCLE_PROJECT_REPONAME}-svc
              servicePort: 80
