version: '2.1'
jobs:
  build:
    docker:
      - image: myparcelcom/build-utils
        auth:
          username: ${DOCKER_CLOUD_USER}
          password: ${DOCKER_CLOUD_PASSWORD}
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Authenticate AWS ECR
          command: ecr-login
      - run:
          name: Building and Pushing Docker images
          command: |
            NS=$(env_namespace)
            eval $(aws-ssm-params ${NS})
            IMAGE_NAME="${ECR_REGISTRY}/myparcelcom/api-specification:$(image_tag --next-gen)"
            docker build \
              -t ${IMAGE_NAME} \
              --build-arg REGISTRY=${ECR_REGISTRY} \
              --build-arg API_HOST=${API_HOST} \
              --build-arg AUTH_HOST=${AUTH_HOST} \
              -f docker/build/Dockerfile .
            docker push ${IMAGE_NAME}

workflows:
  build:
    jobs:
      - build:
          context: [ "aws", "docker_cloud" ]
          filters:
            branches:
              only:
                - master
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+$/
