#!/usr/bin/env bash

echo -e "\033[0;30;47m Bundling spec \033[0m"
docker compose run --rm -T bundler bash -c "
mkdir -p dist
json-refs resolve root.json -f > dist/swagger.json
"

echo -e "\033[0;30;47m Injecting vars \033[0m"
# Escape "/" characters to avoid conflict with sed.
API_HOST=${API_HOST//\//\\/}
AUTH_HOST=${AUTH_HOST//\//\\/}
RELEASE_VERSION=${RELEASE_VERSION//\//\\/}
TRACKING_PAGE_HOST=${TRACKING_PAGE_HOST//\//\\/}

docker compose run --rm -T bundler bash -c "
sed -i 's/\$API_HOST/${API_HOST}/' dist/swagger.json
sed -i 's/\$AUTH_HOST/${AUTH_HOST}/' dist/swagger.json
sed -i 's/\$RELEASE_VERSION/${RELEASE_VERSION}/' dist/swagger.json
sed -i 's/\$TRACKING_PAGE_HOST/${TRACKING_PAGE_HOST}/' dist/swagger.json
"
