#!/usr/bin/env bash

# Check if inotifywait is installed
if ! command -v inotifywait &> /dev/null
then
    echo "inotifywait could not be found. Please install it using:"
    echo "sudo apt-get install inotify-tools -y"
    exit 1
fi

# Check if xdotool is installed
if ! command -v xdotool &> /dev/null
then
    echo "xdotool could not be found. Please install it using:"
    echo "sudo apt-get install xdotool -y"
    exit 1
fi

xdg-open https://api-specification.localhost.private

echo -e "\033[0;30;47m Watching for changes... \033[0m"

# Watch for changes in the ./specification and its subdirectories using inotifywait
inotifywait -r -m ./specification -e close_write < /dev/null |
while read path action file; do
    if [[ "$file" != *~ ]]; then
      ./mp/bundle
    fi
done
